### ISSUE TITLE
ScenarioControllerでjumpするときの条件付け

### ISSUE THREAD

**Issue by mori08** [mori08/IchiNoIchi#47]
RecordSetを参照して飛ぶ  
ANDができるようにしたい

```toml
[[Scenario]]
  [[Scenario.jump]]
    jump = "ジャンプ先のシナリオ名"
    record = ["Record名_1", "Record名_2"]
```
